//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por Estructura 2do. Avance.rc
//
#define IDOK2                           1
#define btn_registrarse                 2
#define btn_cargaro_foto_mecanicos      3
#define Ventana_Principal               4
#define Ventana_Para_Registrarse        5
#define Lista_Clientes                  6
#define edc_celular_mecanico            7
#define cmb_turno_mecanicos             8
#define Ventana_Registro_Clientes       9
#define edc_id_get                      10
#define edc_ver_especialidad            11
#define edc_mostrar_numero              12
#define Fotito                          13
#define Ventana_General                 105
#define IDR_MENU1                       107
#define Ventana_Registrar_Paquetes_Servicios 108
#define Ventana_Registrar_Mecanicos     110
#define IDD_DIALOG1                     111
#define Consulta_Citas                  112
#define Ventana_registro_citas          114
#define heap                            120
#define edc_usuario                     1001
#define edc_contrasenia                 1002
#define btn_ingresar                    1003
#define edc_registro_usuario            1004
#define edc_registro_contrasenia        1005
#define edc_registro_nombrecompleto     1006
#define btn_aceptar                     1007
#define btn_regresar                    1008
#define Lista_M                         1009
#define edc_dias_laborales              1010
#define edc_ver_turnos                  1011
#define edc_ver_numero                  1012
#define btn_eliminar_packs              1013
#define edc_id_packs                    1014
#define edc_full_name_mecanico          1015
#define edc_clave_paquetes              1016
#define edc_costo_paquetes              1017
#define edc_descripccion_paquetes       1018
#define btn_add_packs                   1019
#define btn_regresar_packs              1020
#define edc_costo_paquetes2             1021
#define edc_clave_paquetes2             1022
#define edc_costo_get                   1023
#define edc_descripccion_get            1024
#define edc_id_packs2                   1025
#define lunes                           1026
#define cmb_especialidades_mecanicos    1027
#define martes                          1028
#define miercoles                       1029
#define jueves                          1030
#define viernes                         1031
#define sabado                          1032
#define domingo                         1033
#define btn_aceptar_mecanicos           1034
#define btn_regresar_mecanicos          1035
#define Cargar_Foto_Mecanico            1036
#define edc_num_mecanico                1037
#define Edc_Editar_Mecanico             1039
#define btn_Editar_Cliente              1040
#define Edc_Eliminar_Mecanico           1041
#define btn_eliminar_cliente            1042
#define edc_nombre_cliente              1054
#define edc_numero_cliente              1055
#define edc_placas_cliente              1056
#define edc_marca_cliente               1057
#define edc_modelo_carrocliente         1058
#define edc_anio_vehiculo_cliente       1059
#define edc_km_carro_cliente            1060
#define edc_telefono_cliente            1061
#define edc_direccion_cliente           1062
#define btn_aceptar_cliente             1063
#define btn_regresar_cliente            1064
#define edc_telefono_clientexd          1065
#define direccion_clientexd             1066
#define Lista_Citas_Clientes            1067
#define edc_kilometraje_cliente_xd      1068
#define edc_placas_cliente_carro_xd     1069
#define edc_carro_marca_clientexd       1070
#define edc_carro_anio_cliente          1071
#define Set_Fecha                       1072
#define edc_mostrar_fecha_cita          1073
#define edc_mostrar_cliente_cita        1074
#define edc_mostrar_mecanico_cita       1075
#define btn_regresar_mostrar_cita       1076
#define edc_mostrar_hora_cita           1077
#define Set_Time                        1078
#define Lista_Citas                     1079
#define edc_mostrar_servicio_cita       1080
#define Fotito_Mecanico                 1081
#define IDC_EDIT2                       1082
#define edc_edit_cita_id2               1084
#define edc_edit_cita_fecha2            1085
#define Lista_Citas_Mecanicos           1090
#define edc_id_clientexd                1091
#define aceptar_cita                    1092
#define regresar_cita                   1093
#define modelo_carro_cliente_xd         1094
#define IDC_EDIT1                       1095
#define IDOK_xd                         1096
#define IDC_EDIT4                       1097
#define list_before_ordenar_mecanicos2  1098
#define ordenar_heapsort                1099
#define ultimo_regresar_xd              1100
#define list_paquetes                   1101
#define edc_clave_get                   1102
#define edc_descripccion_paquetes2      1103
#define cmb_especialidades_mecanicos_citas 1104
#define btn_regresar_packs2             1105
#define IDC_LIST1                       1106
#define Lista_packs_show                1107
#define IDC_EDIT3                       1108
#define list_after_ordenar_mecanicos    1109
#define IDC_BUTTON1                     1110
#define Pestania_1                      40003
#define Pestania_2                      40004
#define Pestania_3                      40006
#define Pestania_4                      40008
#define ID_PESTA40009                   40009
#define Pestania_5                      40010
#define ID_PESTA40011                   40011
#define Pestania_6                      40012
#define ID_PESTA40013                   40013
#define ID_PESTA40014                   40014
#define pestania_6_1                    40015
#define ID_PESTA40016                   40016
#define ID_SALIR_SALIRXD                40017
#define salir_sistema                   40018
#define salir_sistema_                  40019

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        122
#define _APS_NEXT_COMMAND_VALUE         40020
#define _APS_NEXT_CONTROL_VALUE         1106
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
